# Generated by Django 3.2.4 on 2021-06-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0002_auto_20210525_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'ToDo'), (1, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'ToDo'), (1, 'Done')], default=0),
        ),
    ]
