# Generated by Django 3.2.4 on 2021-06-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0003_auto_20210605_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=48),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
