# Generated by Django 3.2.7 on 2021-09-12 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0005_auto_20210912_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 12, 11, 51, 343523, tzinfo=utc), null=True),
        ),
    ]
