# Generated by Django 3.2.7 on 2021-09-17 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0007_alter_task_deadline_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 17, 5, 44, 378260, tzinfo=utc), null=True),
        ),
    ]
