# Generated by Django 3.2.7 on 2021-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrack', '0012_alter_task_deadline_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_in',
            field=models.DateTimeField(null=True),
        ),
    ]
